version: '3.7'

services:
  db:
    image: postgis/postgis
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./weatherdb:/var/lib/postgresql/data/
      - ./WeatherData/:/app/WeatherData/
      - ./api/:/app/api/
      - ./manage.py:/app/manage.py
  django_gunicorn:
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn